/*
 * This file was automatically generated by UTestGen and EvoSuite
 * Fri Feb 21 15:27:17 GMT 2025
 */

package edu.stanford.nlp.pipeline;

import edu.stanford.nlp.ling.CoreAnnotation;
import edu.stanford.nlp.ling.CoreAnnotations;
import edu.stanford.nlp.ling.CoreLabel;
import edu.stanford.nlp.process.CoreLabelTokenFactory;
import edu.stanford.nlp.sequences.TrueCasingForNISTDocumentReaderAndWriter;
import edu.stanford.nlp.util.CoreMap;
import org.junit.Test;

import java.util.*;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.*;

public class CleanXmlAnnotator_ESTest6 {

    @Test
    public void testSetDocAnnotationPatterns() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setDocAnnotationPatterns((String) null);
        assertTrue(CleanXmlAnnotator.DEFAULT_ALLOW_FLAWS);
    }

    @Test
    public void testCreatesCleanXmlAnnotatorTakingNoArgumentsAndProcessAndProcessReturningListWhereIsEmptyIsFalse0() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        CoreLabel coreLabel0 = new CoreLabel();
        CoreLabel coreLabel1 = CoreLabel.wordFromString("doctype");
        coreLabel1.setWord("</3disd>");
        coreLabel0.setWord("turn");
        List<CoreLabel> list0 = List.of(coreLabel1, coreLabel0, coreLabel1, coreLabel0, coreLabel1, coreLabel1, coreLabel1);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertEquals(2, coreLabel0.size());
        assertEquals(2, list1.size());
    }

    @Test
    public void testProcessThrowsIllegalArgumentException0() throws Throwable  {
        CoreLabel coreLabel0 = CoreLabel.wordFromString((String) null);
        coreLabel0.setWord("<Jjeto>");
        CoreLabel coreLabel1 = new CoreLabel();
        coreLabel1.setWord("</secin>");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel1, coreLabel1, coreLabel0, coreLabel1);
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator("", ".*", "", false);
        // Undeclared exception!
        try {
            cleanXmlAnnotator0.process(list0);
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // Mismatched tags: </secin> closed a <Jjeto> tag.
            //
            verifyException("edu.stanford.nlp.pipeline.CleanXmlAnnotator", e);
        }
    }

    @Test
    public void testCreatesCleanXmlAnnotatorTaking4ArgumentsAndCallsProcess0() throws Throwable  {
        CoreLabel coreLabel0 = CoreLabel.wordFromString((String) null);
        CoreLabel coreLabel1 = new CoreLabel(coreLabel0);
        coreLabel1.setWord("</disd>");
        coreLabel0.setWord("<da/A=time>");
        List<CoreLabel> list0 = List.of(coreLabel1, coreLabel1, coreLabel0, coreLabel1, coreLabel0, coreLabel1, coreLabel1);
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator("", "clean.quoteauthorattributes", "clean.ssplitDiscardTokens", true);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertTrue(list1.isEmpty());
    }

    @Test
    public void testProcessAndSetSingleSentenceTagMatcherAndProcessReturningListWhereIsEmptyIsTrue0() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setSingleSentenceTagMatcher(".*");
        CoreLabel coreLabel0 = CoreLabel.wordFromString((String) null);
        coreLabel0.setWord("<Eu}7m/>");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertFalse(list1.contains(coreLabel0));
    }

    @Test
    public void testProcessAndSetSingleSentenceTagMatcherAndProcessReturningListWhereIsEmptyIsFalse0() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setSingleSentenceTagMatcher(".*");
        CoreLabel coreLabel0 = CoreLabel.wordFromString("datetime|date");
        CoreLabel coreLabel1 = new CoreLabel(45);
        coreLabel1.setWord("</@BDsec-Po`>");
        List<CoreLabel> list0 = List.of(coreLabel1, coreLabel0, coreLabel1, coreLabel0, coreLabel0, coreLabel1, coreLabel0);
        cleanXmlAnnotator0.process(list0);
        assertEquals(5, coreLabel0.size());
    }

    @Test
    public void testProcessAndSetSingleSentenceTagMatcherAndProcessReturningListWhereIsEmptyIsTrue1() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setSingleSentenceTagMatcher("datetime|date");
        CoreLabel coreLabel0 = new CoreLabel();
        coreLabel0.setWord("<single>");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertFalse(list1.contains(coreLabel0));
    }

    @Test
    public void testProcessThrowsIllegalArgumentException1() throws Throwable  {
        CoreLabel coreLabel0 = CoreLabel.wordFromString((String) null);
        coreLabel0.setWord("zLuQ)=.]");
        CoreLabel coreLabel1 = new CoreLabel();
        coreLabel1.setWord("</secin>");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel1, coreLabel1, coreLabel0, coreLabel1);
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator("", ".*", "", false);
        // Undeclared exception!
        try {
            cleanXmlAnnotator0.process(list0);
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // Got a close tag </secin> which does not match any open tag
            //
            verifyException("edu.stanford.nlp.pipeline.CleanXmlAnnotator", e);
        }
    }

    @Test
    public void testProcessThrowsIllegalArgumentException2() throws Throwable  {
        CoreLabel coreLabel0 = CoreLabel.wordFromString((String) null);
        coreLabel0.setWord("<Jjeto>");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0);
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator("", ".*", "", false);
        // Undeclared exception!
        try {
            cleanXmlAnnotator0.process(list0);
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("edu.stanford.nlp.pipeline.CleanXmlAnnotator", e);
        }
    }

    @Test
    public void testProcessAndSetSectionTagMatcher0() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setSectionTagMatcher(".*");
        CoreLabel coreLabel0 = CoreLabel.wordFromString("speaker");
        CoreLabelTokenFactory coreLabelTokenFactory0 = new CoreLabelTokenFactory(true);
        CoreLabel coreLabel1 = coreLabelTokenFactory0.makeToken("<st}/>", "turn", 24, 24);
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel1, coreLabel1, coreLabel1, coreLabel0, coreLabel0, coreLabel1);
        cleanXmlAnnotator0.process(list0);
        assertEquals(5, coreLabel0.size());
    }

    @Test
    public void testProcessAndSetSectionTagMatcher1() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setSectionTagMatcher(".*");
        CoreLabel coreLabel0 = new CoreLabel();
        coreLabel0.setWord("<section>");
        Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class0 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
        coreLabel0.set(class0, 14);
        CoreLabel coreLabel1 = new CoreLabel(14);
        coreLabel1.setWord("</section>");
        CoreLabel coreLabel2 = CoreLabel.wordFromString("");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel2, coreLabel1, coreLabel1, coreLabel1, coreLabel0, coreLabel2);
        cleanXmlAnnotator0.process(list0);
        assertEquals(7, coreLabel2.size());
    }

    @Test
    public void testProcessAndSetSectionTagMatcherAndProcessReturningListWhereIsEmptyIsTrue() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setSectionTagMatcher(".*");
        CoreLabel coreLabel0 = CoreLabel.wordFromString((String) null);
        coreLabel0.setWord("<section>");
        Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class0 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
        coreLabel0.set(class0, 14);
        CoreLabel coreLabel1 = new CoreLabel(14);
        coreLabel1.setWord("</section>");
        List<CoreLabel> list0 = List.of(coreLabel1, coreLabel0, coreLabel1, coreLabel1, coreLabel0, coreLabel1, coreLabel1);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertTrue(list1.isEmpty());
    }

    @Test
    public void testProcessThrowsNullPointerException() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setQuoteTagMatcher(".*");
        CoreLabel coreLabel0 = new CoreLabel();
        CoreLabelTokenFactory coreLabelTokenFactory0 = new CoreLabelTokenFactory();
        CoreLabel coreLabel1 = coreLabelTokenFactory0.makeToken("<inlNeDO>", "", 1795400231, 1795400231);
        List<CoreLabel> list0 = List.of(coreLabel1, coreLabel0, coreLabel1, coreLabel0, coreLabel0, coreLabel1, coreLabel1);
        // Undeclared exception!
        try {
            cleanXmlAnnotator0.process(list0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("edu.stanford.nlp.pipeline.CleanXmlAnnotator", e);
        }
    }

    @Test
    public void testCreatesCleanXmlAnnotatorTakingNoArgumentsAndProcessAndProcessReturningListWhereIsEmptyIsTrue0() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        CoreLabel coreLabel0 = new CoreLabel();
        coreLabel0.setAfter("docid");
        coreLabel0.setWord("<single>");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertTrue(list1.isEmpty());
    }

    @Test
    public void testCreatesCleanXmlAnnotatorTakingNoArgumentsAndProcessAndProcessReturningListWhereIsEmptyIsTrue1() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        CoreLabel coreLabel0 = new CoreLabel();
        coreLabel0.setBefore("docID=doc[id],doctype=doc[type],docsourcetype=doctype[source]");
        coreLabel0.setWord("<single>");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertEquals(0, list1.size());
    }

    @Test
    public void testSetSectionAnnotationPatterns() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setSectionTagMatcher(".*");
        CoreLabel coreLabel0 = CoreLabel.wordFromString("");
        coreLabel0.setWord("<>");
        Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class0 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
        coreLabel0.set(class0, 15);
        cleanXmlAnnotator0.setSectionAnnotationPatterns("docID=,doctype=F>edocsoTcetyp=iftpec");
        CoreLabel coreLabel1 = CoreLabel.wordFromString("");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel0, coreLabel0, coreLabel1, coreLabel0, coreLabel0, coreLabel0);
        cleanXmlAnnotator0.process(list0);
        assertEquals(4, coreLabel1.size());
    }

    @Test
    public void testProcessAndSetSectionTagMatcherAndSetSsplitDiscardTokensMatcher0() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setSsplitDiscardTokensMatcher("speaker");
        cleanXmlAnnotator0.setSectionTagMatcher(".*");
        CoreLabel coreLabel0 = CoreLabel.wordFromString("speaker");
        CoreLabelTokenFactory coreLabelTokenFactory0 = new CoreLabelTokenFactory();
        CoreLabel coreLabel1 = coreLabelTokenFactory0.makeToken("<scPtiZ.5>", "turn", (-16), (-16));
        List<CoreLabel> list0 = List.of(coreLabel1, coreLabel0, coreLabel1, coreLabel0, coreLabel1, coreLabel0, coreLabel1);
        cleanXmlAnnotator0.process(list0);
        assertEquals(5, coreLabel0.size());
    }

    @Test
    public void testProcessAndSetSectionTagMatcherAndSetSsplitDiscardTokensMatcher1() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setSectionTagMatcher(".*");
        CoreLabel coreLabel0 = CoreLabel.wordFromString("speaker");
        cleanXmlAnnotator0.setSsplitDiscardTokensMatcher("/");
        CoreLabelTokenFactory coreLabelTokenFactory0 = new CoreLabelTokenFactory(true);
        CoreLabel coreLabel1 = coreLabelTokenFactory0.makeToken("<scWin>", "turn", 22, 22);
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel1, coreLabel1, coreLabel1, coreLabel0, coreLabel1, coreLabel0);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertTrue(list1.contains(coreLabel0));
    }

    @Test
    public void testProcessAndSetDocTypeTagMatcher0() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        CoreLabel coreLabel0 = CoreLabel.wordFromString((String) null);
        coreLabel0.setWord("<section>");
        cleanXmlAnnotator0.setDocTypeTagMatcher("section");
        CoreLabel coreLabel1 = new CoreLabel();
        coreLabel1.setWord("");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel1, coreLabel0, coreLabel1, coreLabel1, coreLabel0, coreLabel0);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertTrue(list1.contains(coreLabel1));
    }

    @Test
    public void testProcessAndSetDocTypeTagMatcher1() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        CoreLabel coreLabel0 = CoreLabel.wordFromString("");
        CoreLabelTokenFactory coreLabelTokenFactory0 = new CoreLabelTokenFactory();
        CoreLabel coreLabel1 = coreLabelTokenFactory0.makeToken("<inlNeDO>", "", 1795400200, 1795400200);
        cleanXmlAnnotator0.setDocTypeTagMatcher("/");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel1, coreLabel1, coreLabel1, coreLabel1, coreLabel1, coreLabel0);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertEquals(4, coreLabel0.size());
        assertFalse(list1.isEmpty());
    }

    @Test
    public void testProcessAndSetDocIdTagMatcher0() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        CoreLabel coreLabel0 = CoreLabel.wordFromString("speaker");
        CoreLabelTokenFactory coreLabelTokenFactory0 = new CoreLabelTokenFactory(true);
        cleanXmlAnnotator0.setDocIdTagMatcher("/");
        CoreLabel coreLabel1 = coreLabelTokenFactory0.makeToken("<scPtiZ.5>", "turn", 28, 28);
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel1, coreLabel0, coreLabel1, coreLabel1, coreLabel0, coreLabel0);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertTrue(list1.contains(coreLabel0));
    }

    @Test
    public void testProcessAndSetDocIdTagMatcher1() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        CoreLabel coreLabel0 = CoreLabel.wordFromString("datetime|date");
        CoreLabel coreLabel1 = new CoreLabel(coreLabel0);
        coreLabel1.setWord("<single>");
        cleanXmlAnnotator0.setDocIdTagMatcher("single");
        List<CoreLabel> list0 = List.of(coreLabel1, coreLabel0, coreLabel1, coreLabel1, coreLabel0, coreLabel1, coreLabel1);
        cleanXmlAnnotator0.process(list0);
        assertEquals(5, coreLabel0.size());
    }

    @Test
    public void testCreatesCleanXmlAnnotatorTakingNoArgumentsAndProcessAndProcessReturningListWhereIsEmptyIsFalse1() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        CoreLabel coreLabel0 = CoreLabel.wordFromString("speaker");
        coreLabel0.setBefore("speaker");
        CoreLabelTokenFactory coreLabelTokenFactory0 = new CoreLabelTokenFactory();
        CoreLabel coreLabel1 = coreLabelTokenFactory0.makeToken("<st}/2>", "turn", 5, 5);
        List<CoreLabel> list0 = List.of(coreLabel1, coreLabel1, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel1);
        cleanXmlAnnotator0.process(list0);
        assertEquals(6, coreLabel0.size());
    }

    @Test
    public void testCreatesCleanXmlAnnotatorTakingNoArgumentsAndProcessAndProcessReturningListWhereIsEmptyIsFalse2() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        CoreLabel coreLabel0 = CoreLabel.wordFromString("speaker");
        CoreLabelTokenFactory coreLabelTokenFactory0 = new CoreLabelTokenFactory(true);
        coreLabel0.setBefore("");
        CoreLabel coreLabel1 = coreLabelTokenFactory0.makeToken("<scin>", "turn", 22, 22);
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel1, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel1);
        cleanXmlAnnotator0.process(list0);
        assertEquals(6, coreLabel0.size());
    }

    @Test
    public void testProcessAndSetSingleSentenceTagMatcherAndProcessReturningListWhereIsEmptyIsFalse1() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setSingleSentenceTagMatcher(".*");
        CoreLabel coreLabel0 = CoreLabel.wordFromString("");
        CoreLabel coreLabel1 = CoreLabel.wordFromString("<si[g0e>");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel1, coreLabel1, coreLabel0, coreLabel0, coreLabel1, coreLabel1);
        cleanXmlAnnotator0.process(list0);
        assertEquals(6, coreLabel0.size());
    }

    @Test
    public void testCreatesCleanXmlAnnotatorTaking4ArgumentsAndCallsProcess1() throws Throwable  {
        CoreLabel coreLabel0 = CoreLabel.wordFromString("turn");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0);
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator("doctype", (String) null, (String) null, true);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertFalse(list1.contains(coreLabel0));
    }

    @Test
    public void testCreatesCleanXmlAnnotatorTaking4ArgumentsAndProcessAndProcessReturningListWhereIsEmptyIsFalse() throws Throwable  {
        CoreLabel coreLabel0 = CoreLabel.wordFromString("datetime|date");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0);
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator((String) null, "", ".*", true);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertTrue(list1.contains(coreLabel0));
    }

    @Test
    public void testProcessAndSetDiscourseTagsAndProcessReturningListWhereIsEmptyIsTrue() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setDiscourseTags(".*", ".*");
        CoreLabel coreLabel0 = CoreLabel.wordFromString(".*");
        coreLabel0.setWord("</section>");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertFalse(list1.equals((Object)list0));
    }

    @Test
    public void testProcessAndSetDiscourseTagsAndProcessReturningListWhereIsEmptyIsFalse() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setDiscourseTags(".*", ".*");
        CoreLabel coreLabel0 = CoreLabel.wordFromString("<g4>");
        CoreLabel coreLabel1 = new CoreLabel(coreLabel0);
        coreLabel0.setWord("datetime|date");
        CoreLabelTokenFactory coreLabelTokenFactory0 = new CoreLabelTokenFactory();
        CoreLabel coreLabel2 = coreLabelTokenFactory0.makeToken("</etiJ/Kn>", 7, 1057);
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel1, coreLabel1, coreLabel0, coreLabel2, coreLabel1, coreLabel1);
        cleanXmlAnnotator0.process(list0);
        assertEquals(9, coreLabel0.size());
    }

    @Test
    public void testCreatesCleanXmlAnnotatorTakingNoArgumentsAndCallsAnnotate0() throws Throwable  {
        LinkedList<CoreMap> linkedList0 = new LinkedList<CoreMap>();
        Annotation annotation0 = new Annotation(linkedList0);
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.annotate(annotation0);
        assertEquals(4, annotation0.size());
    }

    @Test
    public void testCreatesCleanXmlAnnotatorTakingNoArgumentsAndCallsAnnotate1() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        Annotation annotation0 = new Annotation(".*");
        cleanXmlAnnotator0.annotate(annotation0);
        assertTrue(CleanXmlAnnotator.DEFAULT_ALLOW_FLAWS);
    }

    @Test
    public void testSetTokenBeginTokenEnd() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        CoreLabel coreLabel0 = CoreLabel.wordFromString((String) null);
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0);
        cleanXmlAnnotator0.setTokenBeginTokenEnd(list0);
        assertTrue(CleanXmlAnnotator.DEFAULT_ALLOW_FLAWS);
    }

    @Test
    public void testSetDocAnnotationPatternsThrowsIllegalArgumentException() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        // Undeclared exception!
        try {
            cleanXmlAnnotator0.setDocAnnotationPatterns("docID=docd,octype=doce,docsourcetype=doctypec");
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // Invalid tag pattern: docd for annotation key docID
            //
            verifyException("edu.stanford.nlp.pipeline.CleanXmlAnnotator", e);
        }
    }

    @Test
    public void testSetSectionAnnotationPatternsThrowsIllegalArgumentException() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        // Undeclared exception!
        try {
            cleanXmlAnnotator0.setSectionAnnotationPatterns("docID=docd,octype=doce,docsourcetype=doctypec");
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // Cannot resolve annotation key octype
            //
            verifyException("edu.stanford.nlp.pipeline.CleanXmlAnnotator", e);
        }
    }

    @Test
    public void testFailsToCreateCleanXmlAnnotatorTakingPropertiesThrowsIllegalStateException0() throws Throwable  {
        Properties properties0 = new Properties();
        properties0.setProperty("clean.sentenceendingtags", "p");
        CleanXmlAnnotator cleanXmlAnnotator0 = null;
        try {
            cleanXmlAnnotator0 = new CleanXmlAnnotator(properties0);
            fail("Expecting exception: IllegalStateException");

        } catch(IllegalStateException e) {
            //
            // No match found
            //
            verifyException("java.util.regex.Matcher", e);
        }
    }

    @Test
    public void testFailsToCreateCleanXmlAnnotatorTakingPropertiesThrowsIllegalStateException1() throws Throwable  {
        Properties properties0 = new Properties();
        properties0.setProperty("clean.allowflawedxml", "true");
        CleanXmlAnnotator cleanXmlAnnotator0 = null;
        try {
            cleanXmlAnnotator0 = new CleanXmlAnnotator(properties0);
            fail("Expecting exception: IllegalStateException");

        } catch(IllegalStateException e) {
            //
            // No match found
            //
            verifyException("java.util.regex.Matcher", e);
        }
    }

    @Test
    public void testRequirementsSatisfied() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        Set<Class<? extends CoreAnnotation>> set0 = (Set<Class<? extends CoreAnnotation>>)cleanXmlAnnotator0.requirementsSatisfied();
        assertEquals(0, set0.size());
    }

    @Test
    public void testSetSectionAnnotationPatternsWithEmptyString() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        // Undeclared exception!
        try {
            cleanXmlAnnotator0.setSectionAnnotationPatterns("");
            fail("Expecting exception: IllegalArgumentException");

        } catch(IllegalArgumentException e) {
            //
            // Invalid annotation to tag pattern: 
            //
            verifyException("edu.stanford.nlp.pipeline.CleanXmlAnnotator", e);
        }
    }

    @Test
    public void testRequires() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        Set<Class<? extends CoreAnnotation>> set0 = (Set<Class<? extends CoreAnnotation>>)cleanXmlAnnotator0.requires();
        assertFalse(set0.isEmpty());
    }

    @Test
    public void testSetTokenAnnotationPatterns() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setTokenAnnotationPatterns((String) null);
        assertTrue(CleanXmlAnnotator.DEFAULT_ALLOW_FLAWS);
    }

    @Test
    public void testSetQuoteTagMatcher() throws Throwable  {
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setQuoteTagMatcher(".*");
        CoreLabel coreLabel0 = new CoreLabel();
        coreLabel0.setWord("</@BDsec-Po`>");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertTrue(list1.isEmpty());
    }

    @Test
    public void testCreatesCleanXmlAnnotatorTaking4ArgumentsAndCallsProcess2() throws Throwable  {
        CoreLabel coreLabel0 = CoreLabel.wordFromString("<s9-qv>");
        List<CoreLabel> list0 = List.of(coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0, coreLabel0);
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator((String) null, ".*", (String) null, true);
        List<CoreLabel> list1 = cleanXmlAnnotator0.process(list0);
        assertFalse(list1.equals((Object)list0));
    }

    @Test
    public void failed1(){
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        CoreLabel coreLabel0 = new CoreLabel();
        Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class0 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
        Class<CoreAnnotations.CharacterOffsetEndAnnotation> class1 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
        CoreLabel coreLabel1 = new CoreLabel();
        coreLabel1.setWord("DOC123");
        coreLabel1.set(class0, 8);
        coreLabel1.set(class1, 14);
        coreLabel0.setWord("<datetime>");
        CoreLabel[] objectArray0 = new CoreLabel[6];
        objectArray0[0] = coreLabel0;
        objectArray0[1] = coreLabel1;
        objectArray0[2] = coreLabel0;
        objectArray0[3] = coreLabel0;
        objectArray0[4] = coreLabel1;
        objectArray0[5] = coreLabel1;
        List<CoreLabel> list0 = Arrays.asList(objectArray0);
        Annotation annotation0 = new Annotation("<docid> DOC123 </docid> <datetime> 2025-02-21 </datetime>");
        Class<CoreAnnotations.TokensAnnotation> class2 = CoreAnnotations.TokensAnnotation.class;
        annotation0.set(class2, list0);
        cleanXmlAnnotator0.annotate(annotation0);
    }

    @Test
    public void failed2(){
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setSectionTagMatcher("section");
        cleanXmlAnnotator0.setQuoteTagMatcher("quote");
        CoreLabel coreLabel0 = CoreLabel.wordFromString((String) null);
        coreLabel0.setWord("<section>");
        Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class0 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
        coreLabel0.set(class0, 14);
        Annotation annotation0 = new Annotation((String) null);
        Class<CoreAnnotations.CharacterOffsetEndAnnotation> class1 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
        CoreLabel coreLabel1 = new CoreLabel();
        coreLabel1.setWord("</quote>");
        coreLabel1.set(class1, 14);
        CoreLabel[] objectArray0 = new CoreLabel[14];
        objectArray0[0] = coreLabel0;
        objectArray0[1] = coreLabel0;
        objectArray0[2] = coreLabel1;
        List<CoreLabel> list0 = (List<CoreLabel>)Arrays.asList(objectArray0);
        Class<CoreAnnotations.TokensAnnotation> class2 = CoreAnnotations.TokensAnnotation.class;
        annotation0.set(class2, list0);
// Undeclared exception!
        try {
            cleanXmlAnnotator0.annotate(annotation0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("edu.stanford.nlp.pipeline.CleanXmlAnnotator", e);
        }
    }

    @Test
    public void failed3(){
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setSectionTagMatcher("section");
        CoreLabel coreLabel0 = CoreLabel.wordFromString((String) null);
        coreLabel0.setWord("<section>");
        Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class0 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
        coreLabel0.set(class0, 14);
        CoreLabel coreLabel1 = new CoreLabel(14);
        coreLabel1.setWord("speaker");
        Annotation annotation0 = new Annotation((String) null);
        CoreLabel coreLabel2 = new CoreLabel();
        coreLabel2.setWord("docID=doc[id],doctype=doc[type],docsourcetype=doctype[source]");
        CoreLabel coreLabel3 = CoreLabel.wordFromString("section");
        coreLabel3.setWord("</section>");
        CoreLabel[] objectArray0 = new CoreLabel[14];
        objectArray0[0] = coreLabel0;
        objectArray0[1] = coreLabel0;
        objectArray0[2] = coreLabel2;
        objectArray0[3] = coreLabel1;
        objectArray0[4] = coreLabel1;
        objectArray0[5] = coreLabel2;
        objectArray0[6] = coreLabel3;
        List<CoreLabel> list0 = Arrays.asList(objectArray0);
        Class<CoreAnnotations.TokensAnnotation> class1 = CoreAnnotations.TokensAnnotation.class;
        annotation0.set(class1, list0);
// Undeclared exception!
        try {
            cleanXmlAnnotator0.annotate(annotation0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("edu.stanford.nlp.pipeline.CleanXmlAnnotator", e);
        }
    }

    @Test
    public void failed4(){
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        cleanXmlAnnotator0.setDiscourseTags("turn", "speaker");
        CoreLabel coreLabel0 = new CoreLabel();
        coreLabel0.setWord(".*");
        CoreLabel coreLabel1 = new CoreLabel();
        coreLabel1.setWord("<turn>");
        CoreLabel coreLabel2 = new CoreLabel();
        coreLabel2.setWord("</speaker>");
        CoreLabel[] objectArray0 = new CoreLabel[10];
        objectArray0[0] = coreLabel0;
        objectArray0[1] = coreLabel1;
        objectArray0[2] = coreLabel2;
        objectArray0[3] = coreLabel1;
        objectArray0[4] = coreLabel0;
        List<CoreLabel> list0 = (List<CoreLabel>)Arrays.asList(objectArray0);
        Annotation annotation0 = new Annotation("Hello <turn> How are you </turn> <speaker> John </speaker> said");
        Class<CoreAnnotations.TokensAnnotation> class0 = CoreAnnotations.TokensAnnotation.class;
        annotation0.set(class0, list0);
// Undeclared exception!
        try {
            cleanXmlAnnotator0.annotate(annotation0);
            fail("Expecting exception: NullPointerException");

        } catch(NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("edu.stanford.nlp.pipeline.CleanXmlAnnotator", e);
        }
    }

    @Test
    public void failed5(){
        CleanXmlAnnotator cleanXmlAnnotator0 = new CleanXmlAnnotator();
        CoreLabel coreLabel0 = CoreLabel.wordFromString(".*");
        CoreLabel coreLabel1 = CoreLabel.wordFromString("");
        coreLabel0.setWord("<datetime>");
        CoreLabel[] objectArray0 = new CoreLabel[6];
        objectArray0[0] = coreLabel0;
        objectArray0[1] = coreLabel0;
        objectArray0[2] = coreLabel0;
        objectArray0[3] = coreLabel0;
        objectArray0[4] = coreLabel1;
        objectArray0[5] = coreLabel0;
        List<CoreLabel> list0 = (List<CoreLabel>)Arrays.asList(objectArray0);
        Annotation annotation0 = new Annotation((String) null);
        Class<CoreAnnotations.TokensAnnotation> class0 = CoreAnnotations.TokensAnnotation.class;
        annotation0.set(class0, list0);
        cleanXmlAnnotator0.annotate(annotation0);
    }
}
