/*
 * This file was automatically generated by UTestGen and EvoSuite
 * Tue Apr 15 08:17:08 GMT 2025
 */

package edu.stanford.nlp.pipeline;

import edu.stanford.nlp.ling.CoreAnnotation;
import edu.stanford.nlp.ling.CoreAnnotations;
import edu.stanford.nlp.ling.CoreLabel;
import edu.stanford.nlp.util.ArrayCoreMap;
import edu.stanford.nlp.util.CoreMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.*;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.*;

public class WordsToSentencesAnnotator_ESTest8 {

  @Test(timeout = 4000)
  public void testCreatesWordsToSentencesAnnotatorTaking7ArgumentsAndFailsToCreateWordsToSentencesAnnotatorTaking7ArgumentsThrowsNoClassDefFoundError()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.nonSplitter();
      assertNotNull(wordsToSentencesAnnotator0);
      
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      String string0 = "";
      LinkedHashSet<String> linkedHashSet1 = new LinkedHashSet<String>();
      String string1 = "never";
      WordsToSentencesAnnotator wordsToSentencesAnnotator1 = null;
      try {
        wordsToSentencesAnnotator1 = new WordsToSentencesAnnotator(false, "", linkedHashSet0, linkedHashSet1, "never", "nFs~E/KyOUHUSz(sELq", linkedHashSet1);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class edu.stanford.nlp.ling.tokensregex.TokenSequencePattern
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testCreatesWordsToSentencesAnnotatorTaking7ArgumentsAndCreatesWordsToSentencesAnnotatorTaking7Arguments()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.nonSplitter();
      HashSet<String> hashSet0 = new HashSet<String>();
      WordsToSentencesAnnotator wordsToSentencesAnnotator1 = new WordsToSentencesAnnotator(false, (String) null, hashSet0, hashSet0, "never", (String) null, hashSet0);
      assertFalse(wordsToSentencesAnnotator1.equals((Object)wordsToSentencesAnnotator0));
  }

  @Test(timeout = 4000)
  public void testFailsToCreateWordsToSentencesAnnotatorTaking7ArgumentsThrowsNoClassDefFoundError()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator();
      LinkedHashSet<String> linkedHashSet0 = new LinkedHashSet<String>();
      WordsToSentencesAnnotator wordsToSentencesAnnotator1 = null;
      try {
        wordsToSentencesAnnotator1 = new WordsToSentencesAnnotator(true, "never", linkedHashSet0, linkedHashSet0, "never", "never", linkedHashSet0);
          System.out.println(wordsToSentencesAnnotator1);


                fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class edu.stanford.nlp.ling.tokensregex.TokenSequencePattern
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testAnnotateAndNewlineSplitter0()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "\n";
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.newlineSplitter(stringArray0);
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("A");
      coreLabel0.setOriginalText("A");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      coreLabel0.set(class0, "A");
      Class<CoreAnnotations.AfterAnnotation> class1 = CoreAnnotations.AfterAnnotation.class;
      coreLabel0.set(class1, " ");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class2 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class2, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class3 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class3, 1);
      Class<CoreAnnotations.IsNewlineAnnotation> class4 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel0.set(class4, false);
      CoreLabel coreLabel1 = new CoreLabel();
      coreLabel1.setWord("\n");
      coreLabel1.setOriginalText("\n");
      Class<CoreAnnotations.TextAnnotation> class5 = CoreAnnotations.TextAnnotation.class;
      coreLabel1.set(class5, "\n");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class6 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel1.set(class6, 1);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class7 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel1.set(class7, 2);
      Class<CoreAnnotations.IsNewlineAnnotation> class8 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel1.set(class8, true);
      CoreLabel coreLabel2 = new CoreLabel();
      coreLabel2.setWord("B");
      coreLabel2.setOriginalText("B");
      Class<CoreAnnotations.TextAnnotation> class9 = CoreAnnotations.TextAnnotation.class;
      coreLabel2.set(class9, "B");
      Class<CoreAnnotations.BeforeAnnotation> class10 = CoreAnnotations.BeforeAnnotation.class;
      coreLabel2.set(class10, "");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class11 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel2.set(class11, 2);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class12 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel2.set(class12, 3);
      Class<CoreAnnotations.IsNewlineAnnotation> class13 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel2.set(class13, false);
      CoreLabel[] coreLabelArray0 = new CoreLabel[3];
      coreLabelArray0[0] = coreLabel0;
      coreLabelArray0[1] = coreLabel1;
      coreLabelArray0[2] = coreLabel2;
      List<CoreLabel> list0 = (List<CoreLabel>)Arrays.asList(coreLabelArray0);
      Annotation annotation0 = new Annotation("A\nB");
      Class<CoreAnnotations.TextAnnotation> class14 = CoreAnnotations.TextAnnotation.class;
      annotation0.set(class14, "A\nB");
      Class<CoreAnnotations.TokensAnnotation> class15 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class15, list0);
      wordsToSentencesAnnotator0.annotate(annotation0);
      Class<CoreAnnotations.TokensAnnotation> class16 = CoreAnnotations.TokensAnnotation.class;
      annotation0.get(class16);
      Class<CoreAnnotations.TokensAnnotation> class17 = CoreAnnotations.TokensAnnotation.class;
      ArrayList arrayList0 = (ArrayList)annotation0.get(class17);
      assertFalse(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void testAnnotateAndNewlineSplitterAndAnnotate0()  throws Throwable  {
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("\n");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      coreLabel0.set(class0, "\n");
      Class<CoreAnnotations.OriginalTextAnnotation> class1 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel0.set(class1, "\n");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class2 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class2, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class3 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class3, 1);
      Class<CoreAnnotations.IsNewlineAnnotation> class4 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel0.set(class4, true);
      CoreLabel coreLabel1 = new CoreLabel();
      coreLabel1.setWord("Start");
      Class<CoreAnnotations.TextAnnotation> class5 = CoreAnnotations.TextAnnotation.class;
      coreLabel1.set(class5, "Start");
      Class<CoreAnnotations.OriginalTextAnnotation> class6 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel1.set(class6, "Start");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class7 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel1.set(class7, 1);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class8 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel1.set(class8, 6);
      Class<CoreAnnotations.IsNewlineAnnotation> class9 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel1.set(class9, false);
      CoreLabel coreLabel2 = new CoreLabel();
      coreLabel2.setWord("middle");
      Class<CoreAnnotations.TextAnnotation> class10 = CoreAnnotations.TextAnnotation.class;
      coreLabel2.set(class10, "middle");
      Class<CoreAnnotations.OriginalTextAnnotation> class11 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel2.set(class11, "middle");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class12 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel2.set(class12, 7);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class13 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel2.set(class13, 13);
      Class<CoreAnnotations.IsNewlineAnnotation> class14 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel2.set(class14, false);
      CoreLabel coreLabel3 = new CoreLabel();
      coreLabel3.setWord("end");
      Class<CoreAnnotations.TextAnnotation> class15 = CoreAnnotations.TextAnnotation.class;
      coreLabel3.set(class15, "end");
      Class<CoreAnnotations.OriginalTextAnnotation> class16 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel3.set(class16, "end");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class17 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel3.set(class17, 14);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class18 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel3.set(class18, 17);
      Class<CoreAnnotations.IsNewlineAnnotation> class19 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel3.set(class19, false);
      CoreLabel coreLabel4 = new CoreLabel();
      coreLabel4.setWord("\n");
      Class<CoreAnnotations.TextAnnotation> class20 = CoreAnnotations.TextAnnotation.class;
      Object object0 = coreLabel4.set(class20, "\n");
      Class<CoreAnnotations.OriginalTextAnnotation> class21 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel4.set(class21, "\n");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class22 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel4.set(class22, 17);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class23 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel4.set(class23, 18);
      Class<CoreAnnotations.IsNewlineAnnotation> class24 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel4.set(class24, true);
      CoreLabel[] coreLabelArray0 = new CoreLabel[5];
      coreLabelArray0[0] = coreLabel0;
      coreLabelArray0[1] = coreLabel1;
      coreLabelArray0[2] = coreLabel2;
      coreLabelArray0[3] = coreLabel3;
      coreLabelArray0[4] = coreLabel4;
      List<CoreLabel> list0 = (List<CoreLabel>)Arrays.asList(coreLabelArray0);
      Annotation annotation0 = new Annotation("\nStart middle end\n");
      Class<CoreAnnotations.TextAnnotation> class25 = CoreAnnotations.TextAnnotation.class;
      annotation0.set(class25, "\nStart middle end\n");
      Class<CoreAnnotations.TokensAnnotation> class26 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class26, list0);
      String[] stringArray0 = new String[1];
      stringArray0[0] = "\n";
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.newlineSplitter(stringArray0);
      wordsToSentencesAnnotator0.annotate(annotation0);
      Class<CoreAnnotations.SentencesAnnotation> class27 = CoreAnnotations.SentencesAnnotation.class;
      List<CoreMap> list1 = (List<CoreMap>)annotation0.get(class27);
      list1.size();
      Annotation annotation1 = (Annotation)list1.get(0);
      Class<CoreAnnotations.TextAnnotation> class28 = CoreAnnotations.TextAnnotation.class;
      String string0 = (String)annotation1.get(class28);
      assertFalse(string0.equals((Object)object0));
  }

  @Test(timeout = 4000)
  public void testFailsToCreateWordsToSentencesAnnotatorTakingPropertiesThrowsNoClassDefFoundError()  throws Throwable  {
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("This");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      coreLabel0.set(class0, "This");
      Class<CoreAnnotations.OriginalTextAnnotation> class1 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel0.set(class1, "This");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class2 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class2, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class3 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class3, 4);
      Class<CoreAnnotations.IsNewlineAnnotation> class4 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel0.set(class4, false);
      CoreLabel coreLabel1 = new CoreLabel();
      coreLabel1.setWord("is");
      Class<CoreAnnotations.TextAnnotation> class5 = CoreAnnotations.TextAnnotation.class;
      coreLabel1.set(class5, "is");
      Class<CoreAnnotations.OriginalTextAnnotation> class6 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel1.set(class6, "is");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class7 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel1.set(class7, 5);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class8 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel1.set(class8, 7);
      Class<CoreAnnotations.IsNewlineAnnotation> class9 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel1.set(class9, false);
      CoreLabel coreLabel2 = new CoreLabel();
      coreLabel2.setWord("Mr.");
      Class<CoreAnnotations.TextAnnotation> class10 = CoreAnnotations.TextAnnotation.class;
      coreLabel2.set(class10, "Mr.");
      Class<CoreAnnotations.OriginalTextAnnotation> class11 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel2.set(class11, "Mr.");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class12 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel2.set(class12, 8);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class13 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel2.set(class13, 11);
      Class<CoreAnnotations.IsNewlineAnnotation> class14 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel2.set(class14, false);
      CoreLabel coreLabel3 = new CoreLabel();
      coreLabel3.setWord("Smith");
      Class<CoreAnnotations.TextAnnotation> class15 = CoreAnnotations.TextAnnotation.class;
      coreLabel3.set(class15, "Smith");
      Class<CoreAnnotations.OriginalTextAnnotation> class16 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel3.set(class16, "Smith");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class17 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel3.set(class17, 12);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class18 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel3.set(class18, 17);
      Class<CoreAnnotations.IsNewlineAnnotation> class19 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel3.set(class19, false);
      CoreLabel coreLabel4 = new CoreLabel();
      coreLabel4.setWord(".");
      Class<CoreAnnotations.TextAnnotation> class20 = CoreAnnotations.TextAnnotation.class;
      coreLabel4.set(class20, ".");
      Class<CoreAnnotations.OriginalTextAnnotation> class21 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel4.set(class21, ".");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class22 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel4.set(class22, 17);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class23 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel4.set(class23, 18);
      Class<CoreAnnotations.IsNewlineAnnotation> class24 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel4.set(class24, false);
      CoreLabel coreLabel5 = new CoreLabel();
      coreLabel5.setWord("This");
      Class<CoreAnnotations.TextAnnotation> class25 = CoreAnnotations.TextAnnotation.class;
      coreLabel5.set(class25, "This");
      Class<CoreAnnotations.OriginalTextAnnotation> class26 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel5.set(class26, "This");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class27 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel5.set(class27, 19);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class28 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel5.set(class28, 23);
      Class<CoreAnnotations.IsNewlineAnnotation> class29 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel5.set(class29, false);
      CoreLabel coreLabel6 = new CoreLabel();
      coreLabel6.setWord("is");
      Class<CoreAnnotations.TextAnnotation> class30 = CoreAnnotations.TextAnnotation.class;
      coreLabel6.set(class30, "is");
      Class<CoreAnnotations.OriginalTextAnnotation> class31 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel6.set(class31, "is");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class32 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel6.set(class32, 24);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class33 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel6.set(class33, 26);
      Class<CoreAnnotations.IsNewlineAnnotation> class34 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel6.set(class34, false);
      CoreLabel coreLabel7 = new CoreLabel();
      coreLabel7.setWord("another");
      Class<CoreAnnotations.TextAnnotation> class35 = CoreAnnotations.TextAnnotation.class;
      coreLabel7.set(class35, "another");
      Class<CoreAnnotations.OriginalTextAnnotation> class36 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel7.set(class36, "another");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class37 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel7.set(class37, 27);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class38 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel7.set(class38, 34);
      Class<CoreAnnotations.IsNewlineAnnotation> class39 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel7.set(class39, false);
      CoreLabel coreLabel8 = new CoreLabel();
      coreLabel8.setWord("sentence");
      Class<CoreAnnotations.TextAnnotation> class40 = CoreAnnotations.TextAnnotation.class;
      coreLabel8.set(class40, "sentence");
      Class<CoreAnnotations.OriginalTextAnnotation> class41 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel8.set(class41, "sentence");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class42 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel8.set(class42, 35);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class43 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel8.set(class43, 43);
      Class<CoreAnnotations.IsNewlineAnnotation> class44 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel8.set(class44, false);
      CoreLabel coreLabel9 = new CoreLabel();
      coreLabel9.setWord(".");
      Class<CoreAnnotations.TextAnnotation> class45 = CoreAnnotations.TextAnnotation.class;
      coreLabel9.set(class45, ".");
      Class<CoreAnnotations.OriginalTextAnnotation> class46 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel9.set(class46, ".");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class47 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel9.set(class47, 43);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class48 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel9.set(class48, 44);
      Class<CoreAnnotations.IsNewlineAnnotation> class49 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel9.set(class49, false);
      CoreLabel[] coreLabelArray0 = new CoreLabel[10];
      coreLabelArray0[0] = coreLabel0;
      coreLabelArray0[1] = coreLabel1;
      coreLabelArray0[2] = coreLabel2;
      coreLabelArray0[3] = coreLabel3;
      coreLabelArray0[4] = coreLabel4;
      coreLabelArray0[5] = coreLabel5;
      coreLabelArray0[6] = coreLabel6;
      coreLabelArray0[7] = coreLabel7;
      coreLabelArray0[8] = coreLabel8;
      coreLabelArray0[9] = coreLabel9;
      List<CoreLabel> list0 = (List<CoreLabel>)Arrays.asList(coreLabelArray0);
      Annotation annotation0 = new Annotation("This is Mr. Smith. This is another sentence.");
      Class<CoreAnnotations.TextAnnotation> class50 = CoreAnnotations.TextAnnotation.class;
      annotation0.set(class50, "This is Mr. Smith. This is another sentence.");
      Class<CoreAnnotations.TokensAnnotation> class51 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class51, list0);
      Properties properties0 = new Properties();
      properties0.setProperty("ssplit.boundaryMultiTokenRegex", "Mr.s+Smith.");
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = null;
      try {
        wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator(properties0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class edu.stanford.nlp.ling.tokensregex.TokenSequencePattern
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testNonSplitterThrowsNoClassDefFoundError()  throws Throwable  {
      FileSystemHandling.setPermissions((EvoSuiteFile) null, false, true, true);
      Properties properties0 = new Properties();
      String string0 = "ssplit.boundaryMultiTokenRegex";
      properties0.setProperty("ssplit.boundaryMultiTokenRegex", "ssplit.boundaryMultiTokenRegex");
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = null;
      try {
        wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator(properties0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class edu.stanford.nlp.ling.tokensregex.TokenSequencePattern
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testAnnotateAndCreatesWordsToSentencesAnnotatorTakingNoArguments0()  throws Throwable  {
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("This");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      coreLabel0.set(class0, "This");
      Class<CoreAnnotations.OriginalTextAnnotation> class1 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel0.set(class1, "This");
      Class<CoreAnnotations.IsNewlineAnnotation> class2 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel0.set(class2, false);
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class3 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class3, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class4 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class4, 4);
      CoreLabel coreLabel1 = new CoreLabel();
      coreLabel1.setWord("is");
      Class<CoreAnnotations.TextAnnotation> class5 = CoreAnnotations.TextAnnotation.class;
      coreLabel1.set(class5, "is");
      Class<CoreAnnotations.OriginalTextAnnotation> class6 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel1.set(class6, "is");
      Class<CoreAnnotations.IsNewlineAnnotation> class7 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel1.set(class7, false);
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class8 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel1.set(class8, 5);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class9 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel1.set(class9, 7);
      CoreLabel coreLabel2 = new CoreLabel();
      coreLabel2.setWord("a");
      Class<CoreAnnotations.TextAnnotation> class10 = CoreAnnotations.TextAnnotation.class;
      coreLabel2.set(class10, "a");
      Class<CoreAnnotations.OriginalTextAnnotation> class11 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel2.set(class11, "a");
      Class<CoreAnnotations.IsNewlineAnnotation> class12 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel2.set(class12, false);
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class13 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel2.set(class13, 8);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class14 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel2.set(class14, 9);
      CoreLabel coreLabel3 = new CoreLabel();
      coreLabel3.setWord("sentence");
      Class<CoreAnnotations.TextAnnotation> class15 = CoreAnnotations.TextAnnotation.class;
      coreLabel3.set(class15, "sentence");
      Class<CoreAnnotations.OriginalTextAnnotation> class16 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel3.set(class16, "sentence");
      Class<CoreAnnotations.IsNewlineAnnotation> class17 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel3.set(class17, false);
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class18 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel3.set(class18, 10);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class19 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel3.set(class19, 18);
      CoreLabel coreLabel4 = new CoreLabel();
      coreLabel4.setWord(".");
      Class<CoreAnnotations.TextAnnotation> class20 = CoreAnnotations.TextAnnotation.class;
      coreLabel4.set(class20, ".");
      Class<CoreAnnotations.OriginalTextAnnotation> class21 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel4.set(class21, ".");
      Class<CoreAnnotations.IsNewlineAnnotation> class22 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel4.set(class22, false);
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class23 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel4.set(class23, 18);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class24 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel4.set(class24, 19);
      CoreLabel[] coreLabelArray0 = new CoreLabel[5];
      coreLabelArray0[0] = coreLabel0;
      coreLabelArray0[1] = coreLabel1;
      coreLabelArray0[2] = coreLabel2;
      coreLabelArray0[3] = coreLabel3;
      coreLabelArray0[4] = coreLabel4;
      List<CoreLabel> list0 = (List<CoreLabel>)Arrays.asList(coreLabelArray0);
      Annotation annotation0 = new Annotation("This is a sentence.");
      Class<CoreAnnotations.TextAnnotation> class25 = CoreAnnotations.TextAnnotation.class;
      annotation0.set(class25, "This is a sentence.");
      Class<CoreAnnotations.TokensAnnotation> class26 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class26, list0);
      Class<CoreAnnotations.SectionsAnnotation> class27 = CoreAnnotations.SectionsAnnotation.class;
      ArrayList<CoreMap> arrayList0 = new ArrayList<CoreMap>();
      annotation0.set(class27, arrayList0);
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator();
      wordsToSentencesAnnotator0.annotate(annotation0);
      Class<CoreAnnotations.SentencesAnnotation> class28 = CoreAnnotations.SentencesAnnotation.class;
      List<CoreMap> list1 = (List<CoreMap>)annotation0.get(class28);
      int int0 = list1.size();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void testAnnotateAndNewlineSplitterAndAnnotate1()  throws Throwable  {
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("First");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      coreLabel0.set(class0, "First");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class1 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class1, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class2 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class2, 5);
      Class<CoreAnnotations.OriginalTextAnnotation> class3 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel0.set(class3, "First");
      Class<CoreAnnotations.IsNewlineAnnotation> class4 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel0.set(class4, false);
      CoreLabel coreLabel1 = new CoreLabel();
      coreLabel1.setWord("\n");
      Class<CoreAnnotations.TextAnnotation> class5 = CoreAnnotations.TextAnnotation.class;
      coreLabel1.set(class5, "\n");
      Class<CoreAnnotations.OriginalTextAnnotation> class6 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel1.set(class6, "\n");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class7 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel1.set(class7, 5);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class8 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel1.set(class8, 6);
      Class<CoreAnnotations.IsNewlineAnnotation> class9 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel1.set(class9, true);
      CoreLabel coreLabel2 = new CoreLabel();
      coreLabel2.setWord("\n");
      Class<CoreAnnotations.TextAnnotation> class10 = CoreAnnotations.TextAnnotation.class;
      coreLabel2.set(class10, "\n");
      Class<CoreAnnotations.OriginalTextAnnotation> class11 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel2.set(class11, "\n");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class12 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel2.set(class12, 6);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class13 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel2.set(class13, 7);
      Class<CoreAnnotations.IsNewlineAnnotation> class14 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel2.set(class14, true);
      CoreLabel coreLabel3 = new CoreLabel();
      coreLabel3.setWord("Second");
      Class<CoreAnnotations.TextAnnotation> class15 = CoreAnnotations.TextAnnotation.class;
      coreLabel3.set(class15, "Second");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class16 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel3.set(class16, 7);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class17 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel3.set(class17, 13);
      Class<CoreAnnotations.OriginalTextAnnotation> class18 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel3.set(class18, "Second");
      Class<CoreAnnotations.IsNewlineAnnotation> class19 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel3.set(class19, false);
      List<CoreLabel> list0 = new ArrayList<CoreLabel>();
      list0.add(coreLabel0);
      list0.add(coreLabel1);
      list0.add(coreLabel2);
      list0.add(coreLabel3);
      Annotation annotation0 = new Annotation("First\n\nSecond");
      Class<CoreAnnotations.TextAnnotation> class20 = CoreAnnotations.TextAnnotation.class;
      annotation0.set(class20, "First\n\nSecond");
      Class<CoreAnnotations.TokensAnnotation> class21 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class21, list0);
      String[] stringArray0 = new String[1];
      stringArray0[0] = "\n";
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.newlineSplitter(stringArray0);
      wordsToSentencesAnnotator0.annotate(annotation0);
      Class<CoreAnnotations.SentencesAnnotation> class22 = CoreAnnotations.SentencesAnnotation.class;
      List<CoreMap> list1 = (List<CoreMap>)annotation0.get(class22);
      int int0 = list1.size();
      Annotation annotation1 = (Annotation)list1.get(0);
      Class<CoreAnnotations.LineNumberAnnotation> class23 = CoreAnnotations.LineNumberAnnotation.class;
      annotation1.get(class23);
      Annotation annotation2 = (Annotation)list1.get(1);
      Class<CoreAnnotations.LineNumberAnnotation> class24 = CoreAnnotations.LineNumberAnnotation.class;
      Integer integer0 = (Integer)annotation2.get(class24);
      assertFalse(integer0.equals((Object)int0));
  }

  @Test(timeout = 4000)
  public void testAnnotateAndNewlineSplitterAndAnnotate2()  throws Throwable  {
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("Hello");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      Object object0 = coreLabel0.set(class0, "Hello");
      Class<CoreAnnotations.OriginalTextAnnotation> class1 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel0.set(class1, "Hello");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class2 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class2, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class3 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class3, 5);
      Class<CoreAnnotations.AfterAnnotation> class4 = CoreAnnotations.AfterAnnotation.class;
      coreLabel0.set(class4, " ");
      Class<CoreAnnotations.IsNewlineAnnotation> class5 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel0.set(class5, false);
      CoreLabel coreLabel1 = new CoreLabel();
      coreLabel1.setWord("\n");
      Class<CoreAnnotations.TextAnnotation> class6 = CoreAnnotations.TextAnnotation.class;
      coreLabel1.set(class6, "\n");
      Class<CoreAnnotations.OriginalTextAnnotation> class7 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel1.set(class7, "\n");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class8 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel1.set(class8, 5);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class9 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel1.set(class9, 6);
      Class<CoreAnnotations.IsNewlineAnnotation> class10 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel1.set(class10, true);
      CoreLabel coreLabel2 = new CoreLabel();
      coreLabel2.setWord("world");
      Class<CoreAnnotations.TextAnnotation> class11 = CoreAnnotations.TextAnnotation.class;
      coreLabel2.set(class11, "world");
      Class<CoreAnnotations.OriginalTextAnnotation> class12 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel2.set(class12, "world");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class13 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel2.set(class13, 6);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class14 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel2.set(class14, 11);
      Class<CoreAnnotations.BeforeAnnotation> class15 = CoreAnnotations.BeforeAnnotation.class;
      coreLabel2.set(class15, " ");
      Class<CoreAnnotations.IsNewlineAnnotation> class16 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel2.set(class16, false);
      CoreLabel[] coreLabelArray0 = new CoreLabel[3];
      coreLabelArray0[0] = coreLabel0;
      coreLabelArray0[1] = coreLabel1;
      coreLabelArray0[2] = coreLabel2;
      List<CoreLabel> list0 = (List<CoreLabel>)Arrays.asList(coreLabelArray0);
      Annotation annotation0 = new Annotation("Hello\nworld");
      Class<CoreAnnotations.TextAnnotation> class17 = CoreAnnotations.TextAnnotation.class;
      annotation0.set(class17, "Hello\nworld");
      Class<CoreAnnotations.TokensAnnotation> class18 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class18, list0);
      String[] stringArray0 = new String[1];
      stringArray0[0] = "\n";
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.newlineSplitter(stringArray0);
      wordsToSentencesAnnotator0.annotate(annotation0);
      Class<CoreAnnotations.TokensAnnotation> class19 = CoreAnnotations.TokensAnnotation.class;
      List<CoreLabel> list1 = (List<CoreLabel>)annotation0.get(class19);
      CoreLabel coreLabel3 = list1.get(0);
      CoreLabel coreLabel4 = list1.get(1);
      Class<CoreAnnotations.AfterAnnotation> class20 = CoreAnnotations.AfterAnnotation.class;
      coreLabel3.get(class20);
      Class<CoreAnnotations.BeforeAnnotation> class21 = CoreAnnotations.BeforeAnnotation.class;
      String string0 = (String)coreLabel4.get(class21);
      assertFalse(string0.equals((Object)object0));
  }

  @Test(timeout = 4000)
  public void testAnnotateAndNewlineSplitterAndAnnotate3()  throws Throwable  {
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("alpha");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      coreLabel0.set(class0, "alpha");
      Class<CoreAnnotations.OriginalTextAnnotation> class1 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel0.set(class1, "alpha");
      Class<CoreAnnotations.IsNewlineAnnotation> class2 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel0.set(class2, false);
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class3 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class3, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class4 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class4, 5);
      Class<CoreAnnotations.AfterAnnotation> class5 = CoreAnnotations.AfterAnnotation.class;
      coreLabel0.set(class5, " ");
      CoreLabel coreLabel1 = new CoreLabel();
      coreLabel1.setWord("\n");
      Class<CoreAnnotations.TextAnnotation> class6 = CoreAnnotations.TextAnnotation.class;
      coreLabel1.set(class6, "\n");
      Class<CoreAnnotations.OriginalTextAnnotation> class7 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel1.set(class7, "\n");
      Class<CoreAnnotations.IsNewlineAnnotation> class8 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel1.set(class8, true);
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class9 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel1.set(class9, 5);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class10 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel1.set(class10, 6);
      CoreLabel[] coreLabelArray0 = new CoreLabel[2];
      coreLabelArray0[0] = coreLabel0;
      coreLabelArray0[1] = coreLabel1;
      List<CoreLabel> list0 = (List<CoreLabel>)Arrays.asList(coreLabelArray0);
      Annotation annotation0 = new Annotation("alpha\n");
      Class<CoreAnnotations.TextAnnotation> class11 = CoreAnnotations.TextAnnotation.class;
      Object object0 = annotation0.set(class11, "alpha\n");
      Class<CoreAnnotations.TokensAnnotation> class12 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class12, list0);
      String[] stringArray0 = new String[1];
      stringArray0[0] = "\n";
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.newlineSplitter(stringArray0);
      wordsToSentencesAnnotator0.annotate(annotation0);
      Class<CoreAnnotations.TokensAnnotation> class13 = CoreAnnotations.TokensAnnotation.class;
      List<CoreLabel> list1 = (List<CoreLabel>)annotation0.get(class13);
      list1.size();
      CoreLabel coreLabel2 = list1.get(0);
      Class<CoreAnnotations.AfterAnnotation> class14 = CoreAnnotations.AfterAnnotation.class;
      String string0 = (String)coreLabel2.get(class14);
      assertFalse(string0.equals((Object)object0));
  }

  @Test(timeout = 4000)
  public void testAnnotateAndNewlineSplitter1()  throws Throwable  {
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("\n");
      coreLabel0.setOriginalText("\n");
      Class<CoreAnnotations.IsNewlineAnnotation> class0 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel0.set(class0, true);
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class1 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class1, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class2 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class2, 1);
      List<CoreLabel> list0 = (List<CoreLabel>)Collections.singletonList(coreLabel0);
      Annotation annotation0 = new Annotation("");
      Class<CoreAnnotations.TextAnnotation> class3 = CoreAnnotations.TextAnnotation.class;
      annotation0.set(class3, "");
      Class<CoreAnnotations.TokensAnnotation> class4 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class4, list0);
      String[] stringArray0 = new String[1];
      stringArray0[0] = "\n";
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.newlineSplitter(stringArray0);
      wordsToSentencesAnnotator0.annotate(annotation0);
      Class<CoreAnnotations.SentencesAnnotation> class5 = CoreAnnotations.SentencesAnnotation.class;
      List<CoreMap> list1 = (List<CoreMap>)annotation0.get(class5);
      list1.size();
      Class<CoreAnnotations.TokensAnnotation> class6 = CoreAnnotations.TokensAnnotation.class;
      List<CoreLabel> list2 = (List<CoreLabel>)annotation0.get(class6);
      boolean boolean0 = list2.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void testCreatesWordsToSentencesAnnotatorTakingPropertiesAndCreatesWordsToSentencesAnnotatorTakingProperties0()  throws Throwable  {
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("What");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      coreLabel0.set(class0, "What");
      Class<CoreAnnotations.OriginalTextAnnotation> class1 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel0.set(class1, "What");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class2 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class2, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class3 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class3, 4);
      Class<CoreAnnotations.IsNewlineAnnotation> class4 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel0.set(class4, false);
      CoreLabel coreLabel1 = new CoreLabel();
      coreLabel1.setWord("?");
      Class<CoreAnnotations.TextAnnotation> class5 = CoreAnnotations.TextAnnotation.class;
      coreLabel1.set(class5, "?");
      Class<CoreAnnotations.OriginalTextAnnotation> class6 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel1.set(class6, "?");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class7 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel1.set(class7, 5);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class8 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel1.set(class8, 6);
      Class<CoreAnnotations.IsNewlineAnnotation> class9 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel1.set(class9, false);
      CoreLabel[] coreLabelArray0 = new CoreLabel[2];
      coreLabelArray0[0] = coreLabel0;
      coreLabelArray0[1] = coreLabel1;
      List<CoreLabel> list0 = (List<CoreLabel>)Arrays.asList(coreLabelArray0);
      Annotation annotation0 = new Annotation("What ?");
      Class<CoreAnnotations.TextAnnotation> class10 = CoreAnnotations.TextAnnotation.class;
      annotation0.set(class10, "What ?");
      Class<CoreAnnotations.TokensAnnotation> class11 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class11, list0);
      Properties properties0 = new Properties();
      properties0.setProperty("ssplit.boundariesToDiscard", "?");
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator(properties0);
      wordsToSentencesAnnotator0.annotate(annotation0);
      Class<CoreAnnotations.SentencesAnnotation> class12 = CoreAnnotations.SentencesAnnotation.class;
      List<CoreMap> list1 = (List<CoreMap>)annotation0.get(class12);
      list1.size();
      Annotation annotation1 = (Annotation)list1.get(0);
      Class<CoreAnnotations.TextAnnotation> class13 = CoreAnnotations.TextAnnotation.class;
      String string0 = (String)annotation1.get(class13);
      assertEquals("What", string0);
  }

  @Test(timeout = 4000)
  public void testCreatesWordsToSentencesAnnotatorTakingPropertiesAndCreatesWordsToSentencesAnnotatorTakingProperties1()  throws Throwable  {
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("This");
      coreLabel0.setValue("This");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      coreLabel0.set(class0, "This");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class1 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class1, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class2 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class2, 4);
      Class<CoreAnnotations.IsNewlineAnnotation> class3 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel0.set(class3, false);
      Class<CoreAnnotations.OriginalTextAnnotation> class4 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel0.set(class4, "This");
      CoreLabel coreLabel1 = new CoreLabel();
      coreLabel1.setWord("is");
      coreLabel1.setValue("is");
      Class<CoreAnnotations.TextAnnotation> class5 = CoreAnnotations.TextAnnotation.class;
      coreLabel1.set(class5, "is");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class6 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel1.set(class6, 5);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class7 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel1.set(class7, 7);
      Class<CoreAnnotations.IsNewlineAnnotation> class8 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel1.set(class8, false);
      Class<CoreAnnotations.OriginalTextAnnotation> class9 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel1.set(class9, "is");
      CoreLabel coreLabel2 = new CoreLabel();
      coreLabel2.setWord("a");
      coreLabel2.setValue("a");
      Class<CoreAnnotations.TextAnnotation> class10 = CoreAnnotations.TextAnnotation.class;
      coreLabel2.set(class10, "a");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class11 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel2.set(class11, 8);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class12 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel2.set(class12, 9);
      Class<CoreAnnotations.IsNewlineAnnotation> class13 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel2.set(class13, false);
      Class<CoreAnnotations.OriginalTextAnnotation> class14 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel2.set(class14, "a");
      CoreLabel coreLabel3 = new CoreLabel();
      coreLabel3.setWord("test");
      coreLabel3.setValue("test");
      Class<CoreAnnotations.TextAnnotation> class15 = CoreAnnotations.TextAnnotation.class;
      coreLabel3.set(class15, "test");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class16 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel3.set(class16, 10);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class17 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel3.set(class17, 14);
      Class<CoreAnnotations.IsNewlineAnnotation> class18 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel3.set(class18, false);
      Class<CoreAnnotations.OriginalTextAnnotation> class19 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel3.set(class19, "test");
      CoreLabel coreLabel4 = new CoreLabel();
      coreLabel4.setWord(".");
      coreLabel4.setValue(".");
      Class<CoreAnnotations.TextAnnotation> class20 = CoreAnnotations.TextAnnotation.class;
      coreLabel4.set(class20, ".");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class21 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel4.set(class21, 14);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class22 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel4.set(class22, 15);
      Class<CoreAnnotations.IsNewlineAnnotation> class23 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel4.set(class23, false);
      Class<CoreAnnotations.OriginalTextAnnotation> class24 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel4.set(class24, ".");
      List<CoreLabel> list0 = new ArrayList<CoreLabel>();
      list0.add(coreLabel0);
      list0.add(coreLabel1);
      list0.add(coreLabel2);
      list0.add(coreLabel3);
      list0.add(coreLabel4);
      Annotation annotation0 = new Annotation("This is a test.");
      Class<CoreAnnotations.TextAnnotation> class25 = CoreAnnotations.TextAnnotation.class;
      annotation0.set(class25, "This is a test.");
      Class<CoreAnnotations.TokensAnnotation> class26 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class26, list0);
      Properties properties0 = new Properties();
      properties0.setProperty("ssplit.boundaryTokenRegex", "[.]");
      properties0.setProperty("ssplit.boundaryFollowersRegex", "[\"]");
      properties0.setProperty("ssplit.tokenPatternsToDiscard", "[\"]");
      properties0.setProperty("ssplit.verbose", "false");
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator(properties0);
      wordsToSentencesAnnotator0.annotate(annotation0);
      Class<CoreAnnotations.SentencesAnnotation> class27 = CoreAnnotations.SentencesAnnotation.class;
      List<CoreMap> list1 = (List<CoreMap>)annotation0.get(class27);
      list1.size();
      Annotation annotation1 = (Annotation)list1.get(0);
      Class<CoreAnnotations.TextAnnotation> class28 = CoreAnnotations.TextAnnotation.class;
      annotation1.get(class28);
      assertEquals(7, annotation1.size());
  }

  @Test(timeout = 4000)
  public void testCreatesWordsToSentencesAnnotatorTakingPropertiesAndCreatesWordsToSentencesAnnotatorTakingProperties2()  throws Throwable  {
      Properties properties0 = new Properties();
      properties0.setProperty("ssplit.boundaryTokenRegex", "[.?!]");
      properties0.setProperty("ssplit.boundaryFollowersRegex", "[\"')]]*");
      properties0.setProperty("ssplit.boundariesToDiscard", "<BR>");
      properties0.setProperty("ssplit.htmlBoundariesToDiscard", "div,br");
      properties0.setProperty("ssplit.tokenPatternsToDiscard", "...");
      properties0.setProperty("tokenize.whitespace", "true");
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator(properties0);
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("Hello.");
      coreLabel0.setOriginalText("Hello.");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      coreLabel0.set(class0, "Hello.");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class1 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class1, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class2 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class2, 6);
      Class<CoreAnnotations.IsNewlineAnnotation> class3 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel0.set(class3, false);
      List<CoreLabel> list0 = new ArrayList<CoreLabel>();
      list0.add(coreLabel0);
      Annotation annotation0 = new Annotation("Hello.");
      Class<CoreAnnotations.TextAnnotation> class4 = CoreAnnotations.TextAnnotation.class;
      annotation0.set(class4, "Hello.");
      Class<CoreAnnotations.TokensAnnotation> class5 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class5, list0);
      wordsToSentencesAnnotator0.annotate(annotation0);
      Class<CoreAnnotations.SentencesAnnotation> class6 = CoreAnnotations.SentencesAnnotation.class;
      List<CoreMap> list1 = (List<CoreMap>)annotation0.get(class6);
      list1.size();
      Annotation annotation1 = (Annotation)list1.get(0);
      Class<CoreAnnotations.TextAnnotation> class7 = CoreAnnotations.TextAnnotation.class;
      annotation1.get(class7);
      assertEquals(7, annotation1.size());
  }

  @Test(timeout = 4000)
  public void testAnnotateAndCreatesWordsToSentencesAnnotatorTakingNoArguments1()  throws Throwable  {
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("A");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      coreLabel0.set(class0, "A");
      Class<CoreAnnotations.OriginalTextAnnotation> class1 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel0.set(class1, "A");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class2 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class2, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class3 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class3, 1);
      Class<CoreAnnotations.IsNewlineAnnotation> class4 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel0.set(class4, false);
      CoreLabel coreLabel1 = new CoreLabel();
      coreLabel1.setWord("sentence");
      Class<CoreAnnotations.TextAnnotation> class5 = CoreAnnotations.TextAnnotation.class;
      coreLabel1.set(class5, "sentence");
      Class<CoreAnnotations.OriginalTextAnnotation> class6 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel1.set(class6, "sentence");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class7 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel1.set(class7, 2);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class8 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel1.set(class8, 10);
      Class<CoreAnnotations.IsNewlineAnnotation> class9 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel1.set(class9, false);
      CoreLabel coreLabel2 = new CoreLabel();
      coreLabel2.setWord(".");
      Class<CoreAnnotations.TextAnnotation> class10 = CoreAnnotations.TextAnnotation.class;
      coreLabel2.set(class10, ".");
      Class<CoreAnnotations.OriginalTextAnnotation> class11 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel2.set(class11, ".");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class12 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel2.set(class12, 10);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class13 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel2.set(class13, 11);
      Class<CoreAnnotations.IsNewlineAnnotation> class14 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel2.set(class14, false);
      CoreLabel[] coreLabelArray0 = new CoreLabel[3];
      coreLabelArray0[0] = coreLabel0;
      coreLabelArray0[1] = coreLabel1;
      coreLabelArray0[2] = coreLabel2;
      List<CoreLabel> list0 = (List<CoreLabel>)Arrays.asList(coreLabelArray0);
      Annotation annotation0 = new Annotation("A sentence.");
      Class<CoreAnnotations.TextAnnotation> class15 = CoreAnnotations.TextAnnotation.class;
      annotation0.set(class15, "A sentence.");
      Class<CoreAnnotations.TokensAnnotation> class16 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class16, list0);
      Class<CoreAnnotations.DocIDAnnotation> class17 = CoreAnnotations.DocIDAnnotation.class;
      annotation0.set(class17, "doc-123");
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator();
      wordsToSentencesAnnotator0.annotate(annotation0);
      Class<CoreAnnotations.SentencesAnnotation> class18 = CoreAnnotations.SentencesAnnotation.class;
      List<CoreMap> list1 = (List<CoreMap>)annotation0.get(class18);
      Annotation annotation1 = (Annotation)list1.get(0);
      Class<CoreAnnotations.DocIDAnnotation> class19 = CoreAnnotations.DocIDAnnotation.class;
      annotation1.get(class19);
      assertEquals(8, annotation1.size());
  }

  @Test(timeout = 4000)
  public void testAnnotateThrowsNullPointerExceptionAndNonSplitter()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.nonSplitter();
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("Single");
      coreLabel0.setOriginalText("Single");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      coreLabel0.set(class0, "Single");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class1 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class1, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class2 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class2, 6);
      CoreLabel coreLabel1 = new CoreLabel();
      coreLabel1.setWord("sentence.");
      coreLabel1.setOriginalText("sentence.");
      Class<CoreAnnotations.TextAnnotation> class3 = CoreAnnotations.TextAnnotation.class;
      coreLabel1.set(class3, "sentence.");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class4 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel1.set(class4, 7);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class5 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel1.set(class5, 16);
      CoreLabel[] coreLabelArray0 = new CoreLabel[2];
      coreLabelArray0[0] = coreLabel0;
      coreLabelArray0[1] = coreLabel1;
      List<CoreLabel> list0 = (List<CoreLabel>)Arrays.asList(coreLabelArray0);
      Annotation annotation0 = new Annotation("Single sentence.");
      Class<CoreAnnotations.DocIDAnnotation> class6 = CoreAnnotations.DocIDAnnotation.class;
      annotation0.set(class6, "DOC_42");
      Class<CoreAnnotations.TextAnnotation> class7 = CoreAnnotations.TextAnnotation.class;
      annotation0.set(class7, "Single sentence.");
      Class<CoreAnnotations.TokensAnnotation> class8 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class8, list0);
      // Undeclared exception!
      try { 
        wordsToSentencesAnnotator0.annotate(annotation0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.lang.Boolean.booleanValue()\" because the return value of \"edu.stanford.nlp.ling.CoreLabel.isNewline()\" is null
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testAnnotateThrowsNullPointerExceptionAndCreatesWordsToSentencesAnnotatorTakingBoolean()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator(true);
      Annotation annotation0 = new Annotation("Verbose sentence.");
      List<CoreLabel> list0 = new ArrayList<CoreLabel>();
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("Verbose");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      coreLabel0.set(class0, "Verbose");
      coreLabel0.setIndex(0);
      list0.add(coreLabel0);
      Class<CoreAnnotations.TokensAnnotation> class1 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class1, list0);
      // Undeclared exception!
      try { 
        wordsToSentencesAnnotator0.annotate(annotation0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.lang.Integer.intValue()\" because the return value of \"edu.stanford.nlp.ling.CoreLabel.get(java.lang.Class)\" is null
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testAnnotateAndCreatesWordsToSentencesAnnotatorTakingNoArguments2()  throws Throwable  {
      CoreLabel coreLabel0 = new CoreLabel();
      coreLabel0.setWord("one");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      coreLabel0.set(class0, "one");
      Class<CoreAnnotations.OriginalTextAnnotation> class1 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel0.set(class1, "one");
      Class<CoreAnnotations.AfterAnnotation> class2 = CoreAnnotations.AfterAnnotation.class;
      coreLabel0.set(class2, " ");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class3 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel0.set(class3, 0);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class4 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel0.set(class4, 3);
      Class<CoreAnnotations.IsNewlineAnnotation> class5 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel0.set(class5, false);
      CoreLabel coreLabel1 = new CoreLabel();
      coreLabel1.setWord("two");
      Class<CoreAnnotations.TextAnnotation> class6 = CoreAnnotations.TextAnnotation.class;
      coreLabel1.set(class6, "two");
      Class<CoreAnnotations.OriginalTextAnnotation> class7 = CoreAnnotations.OriginalTextAnnotation.class;
      coreLabel1.set(class7, "two");
      Class<CoreAnnotations.AfterAnnotation> class8 = CoreAnnotations.AfterAnnotation.class;
      coreLabel1.set(class8, "");
      Class<CoreAnnotations.CharacterOffsetBeginAnnotation> class9 = CoreAnnotations.CharacterOffsetBeginAnnotation.class;
      coreLabel1.set(class9, 4);
      Class<CoreAnnotations.CharacterOffsetEndAnnotation> class10 = CoreAnnotations.CharacterOffsetEndAnnotation.class;
      coreLabel1.set(class10, 7);
      Class<CoreAnnotations.IsNewlineAnnotation> class11 = CoreAnnotations.IsNewlineAnnotation.class;
      coreLabel1.set(class11, false);
      CoreLabel[] coreLabelArray0 = new CoreLabel[2];
      coreLabelArray0[0] = coreLabel0;
      coreLabelArray0[1] = coreLabel1;
      List<CoreLabel> list0 = (List<CoreLabel>)Arrays.asList(coreLabelArray0);
      Annotation annotation0 = new Annotation("one two");
      Class<CoreAnnotations.TextAnnotation> class12 = CoreAnnotations.TextAnnotation.class;
      Object object0 = annotation0.set(class12, "one two");
      Class<CoreAnnotations.TokensAnnotation> class13 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class13, list0);
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator();
      wordsToSentencesAnnotator0.annotate(annotation0);
      Class<CoreAnnotations.TokensAnnotation> class14 = CoreAnnotations.TokensAnnotation.class;
      List<CoreLabel> list1 = (List<CoreLabel>)annotation0.get(class14);
      CoreLabel coreLabel2 = list1.get(0);
      Class<CoreAnnotations.AfterAnnotation> class15 = CoreAnnotations.AfterAnnotation.class;
      String string0 = (String)coreLabel2.get(class15);
      assertFalse(string0.equals((Object)object0));
  }

  @Test(timeout = 4000)
  public void testCreatesWordsToSentencesAnnotatorTakingNoArgumentsAndAnnotate()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator();
      LinkedList<CoreMap> linkedList0 = new LinkedList<CoreMap>();
      Annotation annotation0 = new Annotation(linkedList0);
      wordsToSentencesAnnotator0.annotate(annotation0);
      assertEquals(3, annotation0.size());
      
      wordsToSentencesAnnotator0.annotate(annotation0);
      assertEquals(3, annotation0.size());
  }

  @Test(timeout = 4000)
  public void testAnnotateAndNonSplitter()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator();
      wordsToSentencesAnnotator0.requires();
      wordsToSentencesAnnotator0.requires();
      WordsToSentencesAnnotator wordsToSentencesAnnotator1 = WordsToSentencesAnnotator.nonSplitter();
      wordsToSentencesAnnotator1.requirementsSatisfied();
      wordsToSentencesAnnotator1.requires();
      Vector<CoreMap> vector0 = new Vector<CoreMap>();
      vector0.setSize(0);
      Annotation annotation0 = new Annotation(vector0);
      Class<CoreAnnotations.SectionTagAnnotation> class0 = CoreAnnotations.SectionTagAnnotation.class;
      annotation0.get(class0);
      Annotation annotation1 = new Annotation(annotation0);
      CoreAnnotations.NumericObjectAnnotation coreAnnotations_NumericObjectAnnotation0 = new CoreAnnotations.NumericObjectAnnotation();
      Class<Object> class1 = coreAnnotations_NumericObjectAnnotation0.getType();
      annotation1.equals(class1);
      wordsToSentencesAnnotator0.annotate(annotation1);
      wordsToSentencesAnnotator0.requirementsSatisfied();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "";
      WordsToSentencesAnnotator.newlineSplitter(stringArray0);
      wordsToSentencesAnnotator1.requirementsSatisfied();
      WordsToSentencesAnnotator.nonSplitter();
      WordsToSentencesAnnotator.newlineSplitter(stringArray0);
      Annotation annotation2 = new Annotation(vector0);
      wordsToSentencesAnnotator0.annotate(annotation2);
      assertNotSame(annotation2, annotation1);
  }

  @Test(timeout = 4000)
  public void testAnnotateWithNull()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator(true);
      String string0 = "ssplit.htmlBoundariesToDiscard";
      String[] stringArray0 = null;
      Annotation annotation0 = null;
      // Undeclared exception!
      try { 
        wordsToSentencesAnnotator0.annotate((Annotation) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"edu.stanford.nlp.pipeline.Annotation.containsKey(java.lang.Class)\" because \"annotation\" is null
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testAnnotateThrowsIllegalArgumentExceptionAndCreatesWordsToSentencesAnnotatorTakingBoolean()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator(true);
      Annotation annotation0 = new Annotation("");
      // Undeclared exception!
      try { 
        wordsToSentencesAnnotator0.annotate(annotation0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // WordsToSentencesAnnotator: unable to find words/tokens in: 
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testCreatesWordsToSentencesAnnotatorTakingProperties()  throws Throwable  {
      Properties properties0 = new Properties();
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator(properties0);
  }

  @Test(timeout = 4000)
  public void testCreatesWordsToSentencesAnnotatorTakingPropertiesAndCreatesWordsToSentencesAnnotatorTakingProperties3()  throws Throwable  {
      Properties properties0 = new Properties();
      CoreAnnotations.SectionTagAnnotation coreAnnotations_SectionTagAnnotation0 = new CoreAnnotations.SectionTagAnnotation();
      Object object0 = new Object();
      properties0.put(coreAnnotations_SectionTagAnnotation0, object0);
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator(properties0);
      String[] stringArray0 = new String[6];
      // Undeclared exception!
      try { 
        properties0.contains((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.concurrent.ConcurrentHashMap", e);
      }
  }

  @Test(timeout = 4000)
  public void testNewlineSplitterThrowsIllegalArgumentException()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator(true);
      wordsToSentencesAnnotator0.requirementsSatisfied();
      WordsToSentencesAnnotator.nonSplitter();
      String[] stringArray0 = new String[5];
      stringArray0[0] = "dHG8nk R)ohYa&2j";
      stringArray0[1] = "";
      stringArray0[2] = "=Hh E>Qf{?Cb_G<K";
      stringArray0[3] = "never";
      stringArray0[4] = "ssplit.htmlBoundariesToDiscard";
      WordsToSentencesAnnotator.newlineSplitter(stringArray0);
      WordsToSentencesAnnotator wordsToSentencesAnnotator1 = WordsToSentencesAnnotator.nonSplitter();
      Annotation annotation0 = new Annotation("]B/9l#4");
      wordsToSentencesAnnotator1.requirementsSatisfied();
      ArrayCoreMap.listener = null;
      // Undeclared exception!
      try { 
        wordsToSentencesAnnotator1.annotate(annotation0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // WordsToSentencesAnnotator: unable to find words/tokens in: ]B/9l#4
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testAnnotateThrowsIllegalArgumentExceptionAndCreatesWordsToSentencesAnnotatorTakingNoArguments()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator();
      Annotation annotation0 = new Annotation("tokenize.whitespace");
      // Undeclared exception!
      try { 
        wordsToSentencesAnnotator0.annotate(annotation0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // WordsToSentencesAnnotator: unable to find words/tokens in: tokenize.whitespace
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testFailsToCreateWordsToSentencesAnnotatorTakingPropertiesThrowsNullPointerException()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = null;
      try {
        wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator((Properties) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.util.Properties.getProperty(String, String)\" because \"properties\" is null
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testAnnotateThrowsIllegalStateException()  throws Throwable  {
      List<CoreLabel> list0 = new ArrayList<CoreLabel>();
      Annotation annotation0 = new Annotation("");
      Class<CoreAnnotations.TextAnnotation> class0 = CoreAnnotations.TextAnnotation.class;
      annotation0.set(class0, "");
      Class<CoreAnnotations.TokensAnnotation> class1 = CoreAnnotations.TokensAnnotation.class;
      annotation0.set(class1, list0);
      Properties properties0 = new Properties();
      properties0.setProperty("ssplit.isOneSentence", "true");
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator(properties0);
      // Undeclared exception!
      try { 
        wordsToSentencesAnnotator0.annotate(annotation0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // unexpected empty sentence: []
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testNewlineSplitterReturningNonNull()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.nonSplitter();
      String[] stringArray0 = new String[8];
      stringArray0[0] = "wy$zQ!_+7D#>sAWv";
      stringArray0[1] = "";
      stringArray0[2] = "crib";
      stringArray0[3] = "r/Q*TD`'nxTb WWx";
      stringArray0[4] = "TBB`T";
      stringArray0[5] = "b";
      stringArray0[6] = "";
      stringArray0[7] = "ssplit.isOneSentence";
      WordsToSentencesAnnotator.newlineSplitter(stringArray0);
      wordsToSentencesAnnotator0.requires();
      WordsToSentencesAnnotator wordsToSentencesAnnotator1 = WordsToSentencesAnnotator.nonSplitter();
      wordsToSentencesAnnotator1.requires();
      WordsToSentencesAnnotator.nonSplitter();
      WordsToSentencesAnnotator.nonSplitter();
      // Undeclared exception!
      try { 
        wordsToSentencesAnnotator1.annotate((Annotation) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"edu.stanford.nlp.pipeline.Annotation.containsKey(java.lang.Class)\" because \"annotation\" is null
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testRequiresThrowsNullPointerException()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.nonSplitter();
      // Undeclared exception!
      try { 
        wordsToSentencesAnnotator0.annotate((Annotation) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"edu.stanford.nlp.pipeline.Annotation.containsKey(java.lang.Class)\" because \"annotation\" is null
         //
         verifyException("edu.stanford.nlp.pipeline.WordsToSentencesAnnotator", e);
      }
  }

  @Test(timeout = 4000)
  public void testNewlineSplitterThrowsNullPointerException()  throws Throwable  {
      String[] stringArray0 = null;
      // Undeclared exception!
      try { 
        WordsToSentencesAnnotator.newlineSplitter((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot read the array length because \"a\" is null
         //
         verifyException("edu.stanford.nlp.util.ArrayUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void testNewlineSplitterWithEmptyArray()  throws Throwable  {
      String[] stringArray0 = new String[0];
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.newlineSplitter(stringArray0);
      assertNotNull(wordsToSentencesAnnotator0);
  }

  @Test(timeout = 4000)
  public void testNonSplitterAndRequirementsSatisfied()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.nonSplitter();
      Set<Class<? extends CoreAnnotation>> set0 = (Set<Class<? extends CoreAnnotation>>)wordsToSentencesAnnotator0.requirementsSatisfied();
      assertEquals(2, set0.size());
  }

  @Test(timeout = 4000)
  public void testNonSplitterAndRequires()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = WordsToSentencesAnnotator.nonSplitter();
      Set<Class<? extends CoreAnnotation>> set0 = (Set<Class<? extends CoreAnnotation>>)wordsToSentencesAnnotator0.requires();
      assertEquals(9, set0.size());
  }

  @Test(timeout = 4000)
  public void testRequires()  throws Throwable  {
      WordsToSentencesAnnotator wordsToSentencesAnnotator0 = new WordsToSentencesAnnotator();
      wordsToSentencesAnnotator0.requires();
      wordsToSentencesAnnotator0.requires();
      wordsToSentencesAnnotator0.requires();
      wordsToSentencesAnnotator0.requires();
      WordsToSentencesAnnotator wordsToSentencesAnnotator1 = WordsToSentencesAnnotator.nonSplitter();
      wordsToSentencesAnnotator1.requirementsSatisfied();
      wordsToSentencesAnnotator0.requirementsSatisfied();
      WordsToSentencesAnnotator wordsToSentencesAnnotator2 = WordsToSentencesAnnotator.nonSplitter();
      WordsToSentencesAnnotator wordsToSentencesAnnotator3 = WordsToSentencesAnnotator.nonSplitter();
      wordsToSentencesAnnotator2.requires();
      Set<Class<? extends CoreAnnotation>> set0 = (Set<Class<? extends CoreAnnotation>>)wordsToSentencesAnnotator3.requirementsSatisfied();
      assertEquals(2, set0.size());
      
      wordsToSentencesAnnotator1.requires();
      WordsToSentencesAnnotator.nonSplitter();
      Set<Class<? extends CoreAnnotation>> set1 = (Set<Class<? extends CoreAnnotation>>)wordsToSentencesAnnotator3.requires();
      assertEquals(9, set1.size());
  }
}
